model:
  checkpoint: model.cpt
  dt: 0.1
  niter: 4
  hidden_dims: 128
  std: 0.7
  integrator: leapfrog
  n_types: 20 
  energy:
    d_model: 256
    ff_dim: 1024
    n_heads: 8
    n_layers: 6
training:
  dataset:
    file: dataset.h5
    batch_size: 5
  accum_iter: 100
  train_log:
    file: train_log.out
  eval_log:
    file: eval_log.out
  lr:
    start: 1e-3
    scheduler:
      type: linear
      start_factor: 1.0
      end_factor: 1e-7
      total_iters: 500
